language: python
sudo: false
cache: pip

python:
  - "3.4"
  - "2.7"

branches:
  only:
    - master

install:
  - python setup.py -q develop
  - pip install -r requirements-test.txt

script:
  - coverage run --source=owm_legacy runtests.py

after_success:
  coveralls
